import Link from "next/link";
import { Heart } from "lucide-react";
import { addToCartAction, removeWishlistAction } from "@/app/storefront-actions";
import { StorefrontFooter, StorefrontHeader } from "@/components/storefront";
import { getPublicWishlist } from "@/lib/supabase/storefront";

export default async function WishlistPage() {
  const wishlist = await getPublicWishlist();
  return <><StorefrontHeader /><main className="page-wrap"><div className="catalogue-heading"><div><p className="editorial-kicker">Saved / 11</p><h1 className="display-title mt-5">Your<br />shortlist.</h1></div><Heart className="text-[var(--rose)]" size={28} /></div>{wishlist.length ? <div className="product-grid">{wishlist.map((entry) => { const product = entry.product; if (!product || !product.is_published) return <article key={entry.id} className="product-card commerce-item-unavailable"><div className="product-image"><span className="product-image-placeholder">Unavailable</span></div><div className="product-card-meta"><div><h2>{product?.name ?? "Product unavailable"}</h2><p className="product-brand">No longer in catalogue</p></div></div><div className="product-actions"><form action={removeWishlistAction}><input type="hidden" name="product_id" value={entry.product_id} /><button className="w-full">Remove from wishlist</button></form></div></article>; return <article key={entry.id} className="product-card"><Link href={`/product/${product.slug}`}><div className="product-image">{product.product_images?.[0]?.image_url ? <img src={product.product_images[0].image_url} alt={product.name} /> : <span className="product-image-placeholder">No image</span>}</div><div className="product-card-meta"><div><h2>{product.name}</h2><p className="product-brand">{product.brand || "Taneja Enterprises"}</p></div></div></Link><div className="product-price"><span>₹{Number(product.selling_price).toLocaleString("en-IN")}</span></div><div className="product-actions"><form action={addToCartAction}><input type="hidden" name="product_id" value={product.id} /><input type="hidden" name="quantity" value={Math.max(1, product.minimum_order_quantity ?? 1)} /><button className="w-full">Add to cart</button></form><form action={removeWishlistAction}><input type="hidden" name="product_id" value={product.id} /><button aria-label={`Remove ${product.name} from wishlist`}><Heart size={15} /></button></form></div></article>; })}</div> : <div className="empty-state"><p className="font-[var(--font-display)] text-3xl text-[var(--plum)]">Nothing saved yet.</p><Link href="/products" className="editorial-button mt-6">Explore products</Link></div>}</main><StorefrontFooter /></>;
}
