import { deleteAddressAction, saveAddressAction } from "@/app/storefront-actions";
import Link from "next/link";
import { StorefrontFooter, StorefrontHeader } from "@/components/storefront";
import { getAddresses } from "@/lib/supabase/storefront";
import { redirect } from "next/navigation";

type Address = { id: string; full_name: string; phone: string; address_line1: string; address_line2?: string | null; city: string; state: string; pincode: string; is_default?: boolean };

function AddressForm({ address }: { address?: Address }) {
  return <form action={saveAddressAction} className="editorial-panel grid gap-3 p-5 sm:grid-cols-2"><input type="hidden" name="id" value={address?.id ?? ""} /><input required name="full_name" placeholder="Full name" defaultValue={address?.full_name ?? ""} className="editorial-input" /><input required name="phone" placeholder="Mobile" defaultValue={address?.phone ?? ""} className="editorial-input" /><input required name="address_line1" placeholder="Address" defaultValue={address?.address_line1 ?? ""} className="editorial-input sm:col-span-2" /><input name="address_line2" placeholder="Apartment, landmark" defaultValue={address?.address_line2 ?? ""} className="editorial-input sm:col-span-2" /><input required name="city" placeholder="City" defaultValue={address?.city ?? ""} className="editorial-input" /><input required name="state" placeholder="State" defaultValue={address?.state ?? ""} className="editorial-input" /><input required name="pincode" placeholder="PIN" defaultValue={address?.pincode ?? ""} className="editorial-input" /><label className="flex items-center gap-2 text-sm text-[var(--muted)]"><input type="checkbox" name="is_default" defaultChecked={address?.is_default} /> Default address</label><button className="editorial-button sm:col-span-2">{address ? "Save changes" : "Add address"}</button></form>;
}

export default async function AddressesPage() {
  const addresses = await getAddresses();
  if (!addresses) redirect("/login?next=/account/addresses");
  return <><StorefrontHeader /><main className="page-wrap"><div className="account-layout"><nav className="account-nav"><p className="editorial-kicker mb-3">Your account</p><Link href="/account">Overview</Link><Link href="/account/profile">Profile</Link><Link href="/account/orders">Orders</Link><Link href="/wishlist">Wishlist</Link></nav><section className="account-main"><p className="editorial-kicker">Account / Addresses</p><h1 className="mt-4">Where you<br />receive.</h1><div className="mt-10"><p className="editorial-kicker mb-3">Add a new address</p><AddressForm /></div><div className="mt-12 space-y-4"><p className="editorial-kicker">Saved addresses</p>{addresses.length ? addresses.map((address) => <article key={address.id} className="editorial-panel p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="font-[var(--font-display)] text-2xl text-[var(--plum)]">{address.full_name} {address.is_default ? <span className="ml-2 align-middle text-xs font-sans font-bold uppercase tracking-[.1em] text-[var(--rose)]">Default</span> : null}</p><p className="body-copy mt-2">{address.address_line1}{address.address_line2 ? `, ${address.address_line2}` : ""}, {address.city}, {address.state} - {address.pincode}<br />{address.phone}</p></div><form action={deleteAddressAction}><input type="hidden" name="id" value={address.id} /><button className="text-action">Delete</button></form></div><details className="mt-5"><summary className="text-action cursor-pointer">Edit address</summary><div className="mt-4"><AddressForm address={address} /></div></details></article>) : <div className="empty-state">No saved addresses yet.</div>}</div></section></div></main><StorefrontFooter /></>;
}
