import { deleteAddressAction, saveAddressAction } from "@/app/storefront-actions";
import { StorefrontHeader } from "@/components/storefront";
import { getAddresses } from "@/lib/supabase/storefront";
import { redirect } from "next/navigation";

function AddressForm({ address }: { address?: { id: string; full_name: string; phone: string; address_line1: string; address_line2?: string | null; city: string; state: string; pincode: string; is_default?: boolean } }) {
  return <form action={saveAddressAction} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-2"><input type="hidden" name="id" value={address?.id ?? ""} /><input required name="full_name" placeholder="Full name" defaultValue={address?.full_name ?? ""} className="rounded-xl border px-3 py-3 text-sm" /><input required name="phone" placeholder="Mobile" defaultValue={address?.phone ?? ""} className="rounded-xl border px-3 py-3 text-sm" /><input required name="address_line1" placeholder="Address" defaultValue={address?.address_line1 ?? ""} className="rounded-xl border px-3 py-3 text-sm sm:col-span-2" /><input name="address_line2" placeholder="Apartment, landmark" defaultValue={address?.address_line2 ?? ""} className="rounded-xl border px-3 py-3 text-sm sm:col-span-2" /><input required name="city" placeholder="City" defaultValue={address?.city ?? ""} className="rounded-xl border px-3 py-3 text-sm" /><input required name="state" placeholder="State" defaultValue={address?.state ?? ""} className="rounded-xl border px-3 py-3 text-sm" /><input required name="pincode" placeholder="PIN" defaultValue={address?.pincode ?? ""} className="rounded-xl border px-3 py-3 text-sm" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="is_default" defaultChecked={address?.is_default} /> Default address</label><button className="rounded-xl bg-[#172d27] px-4 py-3 text-sm font-bold text-white sm:col-span-2">{address ? "Save changes" : "Add address"}</button></form>;
}

export default async function AddressesPage() {
  const addresses = await getAddresses();
  if (!addresses) redirect("/login?next=/account/addresses");
  return <><StorefrontHeader /><main className="mx-auto max-w-4xl px-4 py-8"><h1 className="text-3xl font-black">Addresses</h1><p className="mt-2 text-sm text-slate-500">Only you can view and manage these delivery addresses.</p><section className="mt-6"><h2 className="mb-3 text-xl font-black">Add address</h2><AddressForm /></section><section className="mt-8 space-y-4"><h2 className="text-xl font-black">Saved addresses</h2>{addresses.length ? addresses.map((address) => <article key={address.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="font-bold">{address.full_name} {address.is_default ? <span className="ml-2 rounded-full bg-emerald-100 px-2 py-1 text-xs text-emerald-800">Default</span> : null}</p><p className="mt-1 text-sm text-slate-600">{address.address_line1}{address.address_line2 ? `, ${address.address_line2}` : ""}, {address.city}, {address.state} - {address.pincode}</p><p className="text-sm text-slate-500">{address.phone}</p></div><form action={deleteAddressAction}><input type="hidden" name="id" value={address.id} /><button className="text-sm font-bold text-rose-700">Delete</button></form></div><details className="mt-4"><summary className="cursor-pointer text-sm font-bold text-slate-700">Edit address</summary><div className="mt-4"><AddressForm address={address} /></div></details></article>) : <p className="rounded-2xl bg-slate-50 p-6 text-sm text-slate-500">No saved addresses yet.</p>}</section></main></>;
}