import Link from "next/link";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { ProductGrid, StorefrontFooter, StorefrontHeader } from "@/components/storefront";
import { getActiveCategories, getPublishedProducts } from "@/lib/supabase/storefront";

export default async function ProductsPage({ searchParams }: { searchParams?: Promise<Record<string, string | undefined>> }) {
  const params = (await searchParams) ?? {};
  const [data, categories] = await Promise.all([getPublishedProducts({ query: params.q, category: params.category, brand: params.brand, minPrice: params.min ? Number(params.min) : undefined, maxPrice: params.max ? Number(params.max) : undefined, availability: params.availability, sort: params.sort, page: Number(params.page ?? 1) }), getActiveCategories()]);
  return <><StorefrontHeader /><main className="page-wrap"><div className="catalogue-heading"><div><p className="editorial-kicker">Catalogue / 07</p><h1 className="display-title mt-5">The professional<br />selection.</h1></div><p className="catalogue-count">{data.count} live products</p></div><form method="get" className="catalogue-filters"><input name="q" defaultValue={params.q} placeholder="Search the catalogue" /><select name="category" defaultValue={params.category ?? ""}><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select><select name="availability" defaultValue={params.availability ?? ""}><option value="">Availability</option><option value="in_stock">In stock</option><option value="out_of_stock">Out of stock</option></select><select name="sort" defaultValue={params.sort ?? "newest"}><option value="newest">Newest</option><option value="price_asc">Price low to high</option><option value="price_desc">Price high to low</option></select><button>Apply</button></form><div className="mt-10"><ProductGrid products={data.products} /></div>{data.totalPages > 1 ? <div className="mt-12 flex items-center justify-between border-t border-[var(--line)] pt-5 text-xs font-bold uppercase tracking-[.12em] text-[var(--plum)]"><span>Page {data.page} / {data.totalPages}</span><div className="flex gap-5"><Link href={{ pathname: "/products", query: { ...params, page: String(Math.max(1, data.page - 1)) } }} aria-label="Previous page"><ArrowLeft size={17} /></Link><Link href={{ pathname: "/products", query: { ...params, page: String(Math.min(data.totalPages, data.page + 1)) } }} aria-label="Next page"><ArrowRight size={17} /></Link></div></div> : null}</main><StorefrontFooter /></>;
}
