import Link from "next/link";
import { ProductGrid, StorefrontHeader } from "@/components/storefront";
import { getActiveCategories, getPublishedProducts } from "@/lib/supabase/storefront";

export default async function ProductsPage({ searchParams }: { searchParams?: Promise<Record<string, string | undefined>> }) {
  const params = (await searchParams) ?? {};
  const [data, categories] = await Promise.all([getPublishedProducts({ query: params.q, category: params.category, brand: params.brand, minPrice: params.min ? Number(params.min) : undefined, maxPrice: params.max ? Number(params.max) : undefined, availability: params.availability, sort: params.sort, page: Number(params.page ?? 1) }), getActiveCategories()]);
  return <><StorefrontHeader /><main className="mx-auto max-w-7xl px-4 py-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-500">Catalogue</p><h1 className="text-3xl font-black">Products</h1></div><p className="text-sm text-slate-500">{data.count} products</p></div><form method="get" className="my-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input name="q" defaultValue={params.q} placeholder="Search catalogue" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm" /><select name="category" defaultValue={params.category ?? ""} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select><select name="availability" defaultValue={params.availability ?? ""} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="">All availability</option><option value="in_stock">In stock</option><option value="out_of_stock">Out of stock</option></select><select name="sort" defaultValue={params.sort ?? "newest"} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="newest">Newest</option><option value="price_asc">Price low to high</option><option value="price_desc">Price high to low</option></select><button className="rounded-xl bg-[#172d27] px-4 py-2.5 text-sm font-bold text-white">Apply filters</button></form><ProductGrid products={data.products} />{data.totalPages > 1 ? <div className="mt-8 flex justify-between text-sm"><span>Page {data.page} of {data.totalPages}</span><div className="flex gap-2"><Link href={{ pathname: "/products", query: { ...params, page: String(Math.max(1, data.page - 1)) } }} className="rounded-xl border px-3 py-2">Previous</Link><Link href={{ pathname: "/products", query: { ...params, page: String(Math.min(data.totalPages, data.page + 1)) } }} className="rounded-xl border px-3 py-2">Next</Link></div></div> : null}</main></>;
}
