import { notFound } from "next/navigation";
import { addToCartAction, addWishlistAction, buyNowAction } from "@/app/storefront-actions";
import { StorefrontHeader } from "@/components/storefront";
import { getProductReviews, getPublishedProductBySlug } from "@/lib/supabase/storefront";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const product = await getPublishedProductBySlug((await params).slug); return { title: product?.name ?? "Product unavailable", description: product?.description ?? "Taneja Enterprises catalogue" }; }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const product = await getPublishedProductBySlug((await params).slug);
  if (!product) notFound();
  const reviews = await getProductReviews(product.id);
  const image = product.product_images?.[0]?.image_url;
  const minimum = Math.max(1, Number(product.minimum_order_quantity ?? 1));
  return <><StorefrontHeader /><main className="mx-auto max-w-6xl px-4 py-8"><div className="grid gap-8 md:grid-cols-2"><div className="flex aspect-square items-center justify-center overflow-hidden rounded-3xl bg-slate-100 text-sm text-slate-400">{image ? <img src={image} alt={product.name} className="h-full w-full object-cover" /> : "No image available"}</div><div><p className="text-sm text-slate-500">{product.brand || "Taneja Enterprises"}</p><h1 className="mt-2 text-4xl font-black">{product.name}</h1><p className="mt-3 text-sm text-slate-500">SKU: {product.sku}</p><div className="mt-6 flex items-baseline gap-3"><span className="text-3xl font-black">₹{Number(product.selling_price).toLocaleString("en-IN")}</span>{Number(product.mrp) > Number(product.selling_price) ? <del className="text-slate-400">₹{Number(product.mrp).toLocaleString("en-IN")}</del> : null}</div><p className="mt-2 text-sm text-slate-600">{product.stock_quantity > 0 ? `In stock · Minimum order ${minimum}` : "Out of stock"}</p>{product.description ? <p className="mt-6 whitespace-pre-wrap text-slate-700">{product.description}</p> : null}<div className="mt-7 flex flex-wrap gap-3"><form action={addToCartAction} className="flex items-center gap-2"><input type="hidden" name="product_id" value={product.id} /><input type="number" name="quantity" min={minimum} max={product.stock_quantity} defaultValue={minimum} className="w-24 rounded-xl border border-slate-300 px-3 py-3" /><button disabled={product.stock_quantity <= 0} className="rounded-xl bg-[#172d27] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">Add to cart</button></form><a href={`/checkout?product=${product.id}&quantity=${minimum}`} className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold">Buy now</a><form action={addWishlistAction}><input type="hidden" name="product_id" value={product.id} /><button className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold">Add to wishlist</button></form></div></div></div><section className="mt-10 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black">Specifications</h2><pre className="mt-4 whitespace-pre-wrap font-sans text-sm text-slate-600">{product.specifications ? Object.entries(product.specifications).map(([key, value]) => `${key}: ${value}`).join("\n") : "No specifications provided."}</pre></section><section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black">Customer reviews</h2>{reviews.length ? <div className="mt-4 space-y-3">{reviews.map((review) => <article key={review.id} className="border-b border-slate-100 pb-3 last:border-0"><p className="font-semibold">{review.rating ? `${review.rating}/5` : "Review"}</p><p className="mt-1 text-sm text-slate-600">{review.comment ?? review.body ?? review.content ?? ""}</p></article>)}</div> : <p className="mt-3 text-sm text-slate-500">No reviews yet.</p>}</section></main></>;
}
